// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: client.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TSDataType int32

const (
	TSDataType_TS_DATA_TYPE_UNSPECIFIED TSDataType = 0
	TSDataType_TS_DATA_TYPE_BOOLEAN     TSDataType = 1
	TSDataType_TS_DATA_TYPE_INT32       TSDataType = 2
	TSDataType_TS_DATA_TYPE_INT64       TSDataType = 3
	TSDataType_TS_DATA_TYPE_FLOAT       TSDataType = 4
	TSDataType_TS_DATA_TYPE_DOUBLE      TSDataType = 5
	TSDataType_TS_DATA_TYPE_TEXT        TSDataType = 6
)

// Enum value maps for TSDataType.
var (
	TSDataType_name = map[int32]string{
		0: "TS_DATA_TYPE_UNSPECIFIED",
		1: "TS_DATA_TYPE_BOOLEAN",
		2: "TS_DATA_TYPE_INT32",
		3: "TS_DATA_TYPE_INT64",
		4: "TS_DATA_TYPE_FLOAT",
		5: "TS_DATA_TYPE_DOUBLE",
		6: "TS_DATA_TYPE_TEXT",
	}
	TSDataType_value = map[string]int32{
		"TS_DATA_TYPE_UNSPECIFIED": 0,
		"TS_DATA_TYPE_BOOLEAN":     1,
		"TS_DATA_TYPE_INT32":       2,
		"TS_DATA_TYPE_INT64":       3,
		"TS_DATA_TYPE_FLOAT":       4,
		"TS_DATA_TYPE_DOUBLE":      5,
		"TS_DATA_TYPE_TEXT":        6,
	}
)

func (x TSDataType) Enum() *TSDataType {
	p := new(TSDataType)
	*p = x
	return p
}

func (x TSDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TSDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[0].Descriptor()
}

func (TSDataType) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[0]
}

func (x TSDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TSDataType.Descriptor instead.
func (TSDataType) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

type TSValue struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DataType TSDataType             `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=tidets.datanode.v1.TSDataType" json:"data_type,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*TSValue_BoolValue
	//	*TSValue_Int32Value
	//	*TSValue_Int64Value
	//	*TSValue_FloatValue
	//	*TSValue_DoubleValue
	//	*TSValue_TextValue
	Value         isTSValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TSValue) Reset() {
	*x = TSValue{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TSValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSValue) ProtoMessage() {}

func (x *TSValue) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSValue.ProtoReflect.Descriptor instead.
func (*TSValue) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *TSValue) GetDataType() TSDataType {
	if x != nil {
		return x.DataType
	}
	return TSDataType_TS_DATA_TYPE_UNSPECIFIED
}

func (x *TSValue) GetValue() isTSValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TSValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*TSValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *TSValue) GetInt32Value() int32 {
	if x != nil {
		if x, ok := x.Value.(*TSValue_Int32Value); ok {
			return x.Int32Value
		}
	}
	return 0
}

func (x *TSValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*TSValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *TSValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*TSValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *TSValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*TSValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *TSValue) GetTextValue() string {
	if x != nil {
		if x, ok := x.Value.(*TSValue_TextValue); ok {
			return x.TextValue
		}
	}
	return ""
}

type isTSValue_Value interface {
	isTSValue_Value()
}

type TSValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type TSValue_Int32Value struct {
	Int32Value int32 `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type TSValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,4,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type TSValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,5,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type TSValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,6,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type TSValue_TextValue struct {
	TextValue string `protobuf:"bytes,7,opt,name=text_value,json=textValue,proto3,oneof"`
}

func (*TSValue_BoolValue) isTSValue_Value() {}

func (*TSValue_Int32Value) isTSValue_Value() {}

func (*TSValue_Int64Value) isTSValue_Value() {}

func (*TSValue_FloatValue) isTSValue_Value() {}

func (*TSValue_DoubleValue) isTSValue_Value() {}

func (*TSValue_TextValue) isTSValue_Value() {}

type OpenSessionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Username             string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Version              string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	EnableRpcCompression bool                   `protobuf:"varint,4,opt,name=enable_rpc_compression,json=enableRpcCompression,proto3" json:"enable_rpc_compression,omitempty"`
	FetchSize            int64                  `protobuf:"varint,5,opt,name=fetch_size,json=fetchSize,proto3" json:"fetch_size,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *OpenSessionRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OpenSessionRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *OpenSessionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OpenSessionRequest) GetEnableRpcCompression() bool {
	if x != nil {
		return x.EnableRpcCompression
	}
	return false
}

func (x *OpenSessionRequest) GetFetchSize() int64 {
	if x != nil {
		return x.FetchSize
	}
	return 0
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

func (x *OpenSessionResponse) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *CloseSessionRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

type InsertPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DevicePath    string                 `protobuf:"bytes,2,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	Measurement   string                 `protobuf:"bytes,3,opt,name=measurement,proto3" json:"measurement,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         *TSValue               `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertPointRequest) Reset() {
	*x = InsertPointRequest{}
	mi := &file_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPointRequest) ProtoMessage() {}

func (x *InsertPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPointRequest.ProtoReflect.Descriptor instead.
func (*InsertPointRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *InsertPointRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *InsertPointRequest) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *InsertPointRequest) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

func (x *InsertPointRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InsertPointRequest) GetValue() *TSValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type InsertPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertPointResponse) Reset() {
	*x = InsertPointResponse{}
	mi := &file_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPointResponse) ProtoMessage() {}

func (x *InsertPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPointResponse.ProtoReflect.Descriptor instead.
func (*InsertPointResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

type BatchPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Measurement   string                 `protobuf:"bytes,1,opt,name=measurement,proto3" json:"measurement,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         *TSValue               `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPoint) Reset() {
	*x = BatchPoint{}
	mi := &file_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPoint) ProtoMessage() {}

func (x *BatchPoint) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPoint.ProtoReflect.Descriptor instead.
func (*BatchPoint) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7}
}

func (x *BatchPoint) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

func (x *BatchPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BatchPoint) GetValue() *TSValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type InsertBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DevicePath    string                 `protobuf:"bytes,2,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	Points        []*BatchPoint          `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertBatchRequest) Reset() {
	*x = InsertBatchRequest{}
	mi := &file_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertBatchRequest) ProtoMessage() {}

func (x *InsertBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertBatchRequest.ProtoReflect.Descriptor instead.
func (*InsertBatchRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{8}
}

func (x *InsertBatchRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *InsertBatchRequest) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *InsertBatchRequest) GetPoints() []*BatchPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type InsertBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int32                  `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertBatchResponse) Reset() {
	*x = InsertBatchResponse{}
	mi := &file_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertBatchResponse) ProtoMessage() {}

func (x *InsertBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertBatchResponse.ProtoReflect.Descriptor instead.
func (*InsertBatchResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{9}
}

func (x *InsertBatchResponse) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

type QueryRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DevicePath    string                 `protobuf:"bytes,2,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	Measurement   string                 `protobuf:"bytes,3,opt,name=measurement,proto3" json:"measurement,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"` // 0 表示使用会话 fetch_size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRangeRequest) Reset() {
	*x = QueryRangeRequest{}
	mi := &file_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRangeRequest) ProtoMessage() {}

func (x *QueryRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRangeRequest.ProtoReflect.Descriptor instead.
func (*QueryRangeRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{10}
}

func (x *QueryRangeRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *QueryRangeRequest) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *QueryRangeRequest) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

func (x *QueryRangeRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryRangeRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryRangeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PointData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         *TSValue               `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointData) Reset() {
	*x = PointData{}
	mi := &file_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointData) ProtoMessage() {}

func (x *PointData) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointData.ProtoReflect.Descriptor instead.
func (*PointData) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{11}
}

func (x *PointData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PointData) GetValue() *TSValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type QueryRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*PointData           `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRangeResponse) Reset() {
	*x = QueryRangeResponse{}
	mi := &file_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRangeResponse) ProtoMessage() {}

func (x *QueryRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRangeResponse.ProtoReflect.Descriptor instead.
func (*QueryRangeResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{12}
}

func (x *QueryRangeResponse) GetPoints() []*PointData {
	if x != nil {
		return x.Points
	}
	return nil
}

type ExecuteSQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSQLRequest) Reset() {
	*x = ExecuteSQLRequest{}
	mi := &file_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSQLRequest) ProtoMessage() {}

func (x *ExecuteSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSQLRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSQLRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteSQLRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *ExecuteSQLRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type SQLRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         *TSValue               `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLRow) Reset() {
	*x = SQLRow{}
	mi := &file_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLRow) ProtoMessage() {}

func (x *SQLRow) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLRow.ProtoReflect.Descriptor instead.
func (*SQLRow) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{14}
}

func (x *SQLRow) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SQLRow) GetValue() *TSValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type ExecuteSQLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedRows  int32                  `protobuf:"varint,1,opt,name=affected_rows,json=affectedRows,proto3" json:"affected_rows,omitempty"` // INSERT 时为 1
	Rows          []*SQLRow              `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`                                      // SELECT 结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSQLResponse) Reset() {
	*x = ExecuteSQLResponse{}
	mi := &file_client_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSQLResponse) ProtoMessage() {}

func (x *ExecuteSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSQLResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSQLResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteSQLResponse) GetAffectedRows() int32 {
	if x != nil {
		return x.AffectedRows
	}
	return 0
}

func (x *ExecuteSQLResponse) GetRows() []*SQLRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\x12tidets.datanode.v1\"\x9f\x02\n" +
	"\aTSValue\x12;\n" +
	"\tdata_type\x18\x01 \x01(\x0e2\x1e.tidets.datanode.v1.TSDataTypeR\bdataType\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vint32_value\x18\x03 \x01(\x05H\x00R\n" +
	"int32Value\x12!\n" +
	"\vint64_value\x18\x04 \x01(\x03H\x00R\n" +
	"int64Value\x12!\n" +
	"\vfloat_value\x18\x05 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\x06 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"text_value\x18\a \x01(\tH\x00R\ttextValueB\a\n" +
	"\x05value\"\xbb\x01\n" +
	"\x12OpenSessionRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x124\n" +
	"\x16enable_rpc_compression\x18\x04 \x01(\bR\x14enableRpcCompression\x12\x1d\n" +
	"\n" +
	"fetch_size\x18\x05 \x01(\x03R\tfetchSize\"4\n" +
	"\x13OpenSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\"\x16\n" +
	"\x14CloseSessionResponse\"\xc7\x01\n" +
	"\x12InsertPointRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x1f\n" +
	"\vdevice_path\x18\x02 \x01(\tR\n" +
	"devicePath\x12 \n" +
	"\vmeasurement\x18\x03 \x01(\tR\vmeasurement\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x121\n" +
	"\x05value\x18\x05 \x01(\v2\x1b.tidets.datanode.v1.TSValueR\x05value\"\x15\n" +
	"\x13InsertPointResponse\"\x7f\n" +
	"\n" +
	"BatchPoint\x12 \n" +
	"\vmeasurement\x18\x01 \x01(\tR\vmeasurement\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x121\n" +
	"\x05value\x18\x03 \x01(\v2\x1b.tidets.datanode.v1.TSValueR\x05value\"\x8c\x01\n" +
	"\x12InsertBatchRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x1f\n" +
	"\vdevice_path\x18\x02 \x01(\tR\n" +
	"devicePath\x126\n" +
	"\x06points\x18\x03 \x03(\v2\x1e.tidets.datanode.v1.BatchPointR\x06points\"1\n" +
	"\x13InsertBatchResponse\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x05R\binserted\"\xc5\x01\n" +
	"\x11QueryRangeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x1f\n" +
	"\vdevice_path\x18\x02 \x01(\tR\n" +
	"devicePath\x12 \n" +
	"\vmeasurement\x18\x03 \x01(\tR\vmeasurement\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"\\\n" +
	"\tPointData\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.tidets.datanode.v1.TSValueR\x05value\"K\n" +
	"\x12QueryRangeResponse\x125\n" +
	"\x06points\x18\x01 \x03(\v2\x1d.tidets.datanode.v1.PointDataR\x06points\"D\n" +
	"\x11ExecuteSQLRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\"Y\n" +
	"\x06SQLRow\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.tidets.datanode.v1.TSValueR\x05value\"i\n" +
	"\x12ExecuteSQLResponse\x12#\n" +
	"\raffected_rows\x18\x01 \x01(\x05R\faffectedRows\x12.\n" +
	"\x04rows\x18\x02 \x03(\v2\x1a.tidets.datanode.v1.SQLRowR\x04rows*\xbc\x01\n" +
	"\n" +
	"TSDataType\x12\x1c\n" +
	"\x18TS_DATA_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TS_DATA_TYPE_BOOLEAN\x10\x01\x12\x16\n" +
	"\x12TS_DATA_TYPE_INT32\x10\x02\x12\x16\n" +
	"\x12TS_DATA_TYPE_INT64\x10\x03\x12\x16\n" +
	"\x12TS_DATA_TYPE_FLOAT\x10\x04\x12\x17\n" +
	"\x13TS_DATA_TYPE_DOUBLE\x10\x05\x12\x15\n" +
	"\x11TS_DATA_TYPE_TEXT\x10\x062\xd5\x04\n" +
	"\x16DataNodeSessionService\x12^\n" +
	"\vOpenSession\x12&.tidets.datanode.v1.OpenSessionRequest\x1a'.tidets.datanode.v1.OpenSessionResponse\x12a\n" +
	"\fCloseSession\x12'.tidets.datanode.v1.CloseSessionRequest\x1a(.tidets.datanode.v1.CloseSessionResponse\x12^\n" +
	"\vInsertPoint\x12&.tidets.datanode.v1.InsertPointRequest\x1a'.tidets.datanode.v1.InsertPointResponse\x12^\n" +
	"\vInsertBatch\x12&.tidets.datanode.v1.InsertBatchRequest\x1a'.tidets.datanode.v1.InsertBatchResponse\x12[\n" +
	"\n" +
	"QueryRange\x12%.tidets.datanode.v1.QueryRangeRequest\x1a&.tidets.datanode.v1.QueryRangeResponse\x12[\n" +
	"\n" +
	"ExecuteSQL\x12%.tidets.datanode.v1.ExecuteSQLRequest\x1a&.tidets.datanode.v1.ExecuteSQLResponseB7Z5github.com/hanami/tidets/protocol/grpc-datanode/pb;pbb\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_client_proto_goTypes = []any{
	(TSDataType)(0),              // 0: tidets.datanode.v1.TSDataType
	(*TSValue)(nil),              // 1: tidets.datanode.v1.TSValue
	(*OpenSessionRequest)(nil),   // 2: tidets.datanode.v1.OpenSessionRequest
	(*OpenSessionResponse)(nil),  // 3: tidets.datanode.v1.OpenSessionResponse
	(*CloseSessionRequest)(nil),  // 4: tidets.datanode.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil), // 5: tidets.datanode.v1.CloseSessionResponse
	(*InsertPointRequest)(nil),   // 6: tidets.datanode.v1.InsertPointRequest
	(*InsertPointResponse)(nil),  // 7: tidets.datanode.v1.InsertPointResponse
	(*BatchPoint)(nil),           // 8: tidets.datanode.v1.BatchPoint
	(*InsertBatchRequest)(nil),   // 9: tidets.datanode.v1.InsertBatchRequest
	(*InsertBatchResponse)(nil),  // 10: tidets.datanode.v1.InsertBatchResponse
	(*QueryRangeRequest)(nil),    // 11: tidets.datanode.v1.QueryRangeRequest
	(*PointData)(nil),            // 12: tidets.datanode.v1.PointData
	(*QueryRangeResponse)(nil),   // 13: tidets.datanode.v1.QueryRangeResponse
	(*ExecuteSQLRequest)(nil),    // 14: tidets.datanode.v1.ExecuteSQLRequest
	(*SQLRow)(nil),               // 15: tidets.datanode.v1.SQLRow
	(*ExecuteSQLResponse)(nil),   // 16: tidets.datanode.v1.ExecuteSQLResponse
}
var file_client_proto_depIdxs = []int32{
	0,  // 0: tidets.datanode.v1.TSValue.data_type:type_name -> tidets.datanode.v1.TSDataType
	1,  // 1: tidets.datanode.v1.InsertPointRequest.value:type_name -> tidets.datanode.v1.TSValue
	1,  // 2: tidets.datanode.v1.BatchPoint.value:type_name -> tidets.datanode.v1.TSValue
	8,  // 3: tidets.datanode.v1.InsertBatchRequest.points:type_name -> tidets.datanode.v1.BatchPoint
	1,  // 4: tidets.datanode.v1.PointData.value:type_name -> tidets.datanode.v1.TSValue
	12, // 5: tidets.datanode.v1.QueryRangeResponse.points:type_name -> tidets.datanode.v1.PointData
	1,  // 6: tidets.datanode.v1.SQLRow.value:type_name -> tidets.datanode.v1.TSValue
	15, // 7: tidets.datanode.v1.ExecuteSQLResponse.rows:type_name -> tidets.datanode.v1.SQLRow
	2,  // 8: tidets.datanode.v1.DataNodeSessionService.OpenSession:input_type -> tidets.datanode.v1.OpenSessionRequest
	4,  // 9: tidets.datanode.v1.DataNodeSessionService.CloseSession:input_type -> tidets.datanode.v1.CloseSessionRequest
	6,  // 10: tidets.datanode.v1.DataNodeSessionService.InsertPoint:input_type -> tidets.datanode.v1.InsertPointRequest
	9,  // 11: tidets.datanode.v1.DataNodeSessionService.InsertBatch:input_type -> tidets.datanode.v1.InsertBatchRequest
	11, // 12: tidets.datanode.v1.DataNodeSessionService.QueryRange:input_type -> tidets.datanode.v1.QueryRangeRequest
	14, // 13: tidets.datanode.v1.DataNodeSessionService.ExecuteSQL:input_type -> tidets.datanode.v1.ExecuteSQLRequest
	3,  // 14: tidets.datanode.v1.DataNodeSessionService.OpenSession:output_type -> tidets.datanode.v1.OpenSessionResponse
	5,  // 15: tidets.datanode.v1.DataNodeSessionService.CloseSession:output_type -> tidets.datanode.v1.CloseSessionResponse
	7,  // 16: tidets.datanode.v1.DataNodeSessionService.InsertPoint:output_type -> tidets.datanode.v1.InsertPointResponse
	10, // 17: tidets.datanode.v1.DataNodeSessionService.InsertBatch:output_type -> tidets.datanode.v1.InsertBatchResponse
	13, // 18: tidets.datanode.v1.DataNodeSessionService.QueryRange:output_type -> tidets.datanode.v1.QueryRangeResponse
	16, // 19: tidets.datanode.v1.DataNodeSessionService.ExecuteSQL:output_type -> tidets.datanode.v1.ExecuteSQLResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	file_client_proto_msgTypes[0].OneofWrappers = []any{
		(*TSValue_BoolValue)(nil),
		(*TSValue_Int32Value)(nil),
		(*TSValue_Int64Value)(nil),
		(*TSValue_FloatValue)(nil),
		(*TSValue_DoubleValue)(nil),
		(*TSValue_TextValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		EnumInfos:         file_client_proto_enumTypes,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
