// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: client.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataNodeSessionService_OpenSession_FullMethodName  = "/tidets.datanode.v1.DataNodeSessionService/OpenSession"
	DataNodeSessionService_CloseSession_FullMethodName = "/tidets.datanode.v1.DataNodeSessionService/CloseSession"
	DataNodeSessionService_InsertPoint_FullMethodName  = "/tidets.datanode.v1.DataNodeSessionService/InsertPoint"
	DataNodeSessionService_InsertBatch_FullMethodName  = "/tidets.datanode.v1.DataNodeSessionService/InsertBatch"
	DataNodeSessionService_QueryRange_FullMethodName   = "/tidets.datanode.v1.DataNodeSessionService/QueryRange"
	DataNodeSessionService_ExecuteSQL_FullMethodName   = "/tidets.datanode.v1.DataNodeSessionService/ExecuteSQL"
)

// DataNodeSessionServiceClient is the client API for DataNodeSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataNodeSessionServiceClient interface {
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error)
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
	InsertPoint(ctx context.Context, in *InsertPointRequest, opts ...grpc.CallOption) (*InsertPointResponse, error)
	InsertBatch(ctx context.Context, in *InsertBatchRequest, opts ...grpc.CallOption) (*InsertBatchResponse, error)
	QueryRange(ctx context.Context, in *QueryRangeRequest, opts ...grpc.CallOption) (*QueryRangeResponse, error)
	ExecuteSQL(ctx context.Context, in *ExecuteSQLRequest, opts ...grpc.CallOption) (*ExecuteSQLResponse, error)
}

type dataNodeSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNodeSessionServiceClient(cc grpc.ClientConnInterface) DataNodeSessionServiceClient {
	return &dataNodeSessionServiceClient{cc}
}

func (c *dataNodeSessionServiceClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenSessionResponse)
	err := c.cc.Invoke(ctx, DataNodeSessionService_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeSessionServiceClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, DataNodeSessionService_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeSessionServiceClient) InsertPoint(ctx context.Context, in *InsertPointRequest, opts ...grpc.CallOption) (*InsertPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertPointResponse)
	err := c.cc.Invoke(ctx, DataNodeSessionService_InsertPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeSessionServiceClient) InsertBatch(ctx context.Context, in *InsertBatchRequest, opts ...grpc.CallOption) (*InsertBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertBatchResponse)
	err := c.cc.Invoke(ctx, DataNodeSessionService_InsertBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeSessionServiceClient) QueryRange(ctx context.Context, in *QueryRangeRequest, opts ...grpc.CallOption) (*QueryRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRangeResponse)
	err := c.cc.Invoke(ctx, DataNodeSessionService_QueryRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeSessionServiceClient) ExecuteSQL(ctx context.Context, in *ExecuteSQLRequest, opts ...grpc.CallOption) (*ExecuteSQLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteSQLResponse)
	err := c.cc.Invoke(ctx, DataNodeSessionService_ExecuteSQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataNodeSessionServiceServer is the server API for DataNodeSessionService service.
// All implementations must embed UnimplementedDataNodeSessionServiceServer
// for forward compatibility.
type DataNodeSessionServiceServer interface {
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error)
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	InsertPoint(context.Context, *InsertPointRequest) (*InsertPointResponse, error)
	InsertBatch(context.Context, *InsertBatchRequest) (*InsertBatchResponse, error)
	QueryRange(context.Context, *QueryRangeRequest) (*QueryRangeResponse, error)
	ExecuteSQL(context.Context, *ExecuteSQLRequest) (*ExecuteSQLResponse, error)
	mustEmbedUnimplementedDataNodeSessionServiceServer()
}

// UnimplementedDataNodeSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataNodeSessionServiceServer struct{}

func (UnimplementedDataNodeSessionServiceServer) OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedDataNodeSessionServiceServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedDataNodeSessionServiceServer) InsertPoint(context.Context, *InsertPointRequest) (*InsertPointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertPoint not implemented")
}
func (UnimplementedDataNodeSessionServiceServer) InsertBatch(context.Context, *InsertBatchRequest) (*InsertBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertBatch not implemented")
}
func (UnimplementedDataNodeSessionServiceServer) QueryRange(context.Context, *QueryRangeRequest) (*QueryRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryRange not implemented")
}
func (UnimplementedDataNodeSessionServiceServer) ExecuteSQL(context.Context, *ExecuteSQLRequest) (*ExecuteSQLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSQL not implemented")
}
func (UnimplementedDataNodeSessionServiceServer) mustEmbedUnimplementedDataNodeSessionServiceServer() {
}
func (UnimplementedDataNodeSessionServiceServer) testEmbeddedByValue() {}

// UnsafeDataNodeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataNodeSessionServiceServer will
// result in compilation errors.
type UnsafeDataNodeSessionServiceServer interface {
	mustEmbedUnimplementedDataNodeSessionServiceServer()
}

func RegisterDataNodeSessionServiceServer(s grpc.ServiceRegistrar, srv DataNodeSessionServiceServer) {
	// If the following call panics, it indicates UnimplementedDataNodeSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataNodeSessionService_ServiceDesc, srv)
}

func _DataNodeSessionService_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeSessionServiceServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeSessionService_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeSessionServiceServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNodeSessionService_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeSessionServiceServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeSessionService_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeSessionServiceServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNodeSessionService_InsertPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeSessionServiceServer).InsertPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeSessionService_InsertPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeSessionServiceServer).InsertPoint(ctx, req.(*InsertPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNodeSessionService_InsertBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeSessionServiceServer).InsertBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeSessionService_InsertBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeSessionServiceServer).InsertBatch(ctx, req.(*InsertBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNodeSessionService_QueryRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeSessionServiceServer).QueryRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeSessionService_QueryRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeSessionServiceServer).QueryRange(ctx, req.(*QueryRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNodeSessionService_ExecuteSQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeSessionServiceServer).ExecuteSQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeSessionService_ExecuteSQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeSessionServiceServer).ExecuteSQL(ctx, req.(*ExecuteSQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataNodeSessionService_ServiceDesc is the grpc.ServiceDesc for DataNodeSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataNodeSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tidets.datanode.v1.DataNodeSessionService",
	HandlerType: (*DataNodeSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSession",
			Handler:    _DataNodeSessionService_OpenSession_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _DataNodeSessionService_CloseSession_Handler,
		},
		{
			MethodName: "InsertPoint",
			Handler:    _DataNodeSessionService_InsertPoint_Handler,
		},
		{
			MethodName: "InsertBatch",
			Handler:    _DataNodeSessionService_InsertBatch_Handler,
		},
		{
			MethodName: "QueryRange",
			Handler:    _DataNodeSessionService_QueryRange_Handler,
		},
		{
			MethodName: "ExecuteSQL",
			Handler:    _DataNodeSessionService_ExecuteSQL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client.proto",
}
