// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: server.proto

package pb

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// DataNodeAdminServiceClient is the client API for DataNodeAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataNodeAdminService 面向服务端运维/管理的 RPC（与客户端会话 API 分离）。
// 当前无方法，后续可在此增加 Flush、Stats 等。
type DataNodeAdminServiceClient interface {
}

type dataNodeAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNodeAdminServiceClient(cc grpc.ClientConnInterface) DataNodeAdminServiceClient {
	return &dataNodeAdminServiceClient{cc}
}

// DataNodeAdminServiceServer is the server API for DataNodeAdminService service.
// All implementations must embed UnimplementedDataNodeAdminServiceServer
// for forward compatibility.
//
// DataNodeAdminService 面向服务端运维/管理的 RPC（与客户端会话 API 分离）。
// 当前无方法，后续可在此增加 Flush、Stats 等。
type DataNodeAdminServiceServer interface {
	mustEmbedUnimplementedDataNodeAdminServiceServer()
}

// UnimplementedDataNodeAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataNodeAdminServiceServer struct{}

func (UnimplementedDataNodeAdminServiceServer) mustEmbedUnimplementedDataNodeAdminServiceServer() {}
func (UnimplementedDataNodeAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeDataNodeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataNodeAdminServiceServer will
// result in compilation errors.
type UnsafeDataNodeAdminServiceServer interface {
	mustEmbedUnimplementedDataNodeAdminServiceServer()
}

func RegisterDataNodeAdminServiceServer(s grpc.ServiceRegistrar, srv DataNodeAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedDataNodeAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataNodeAdminService_ServiceDesc, srv)
}

// DataNodeAdminService_ServiceDesc is the grpc.ServiceDesc for DataNodeAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataNodeAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tidets.datanode.v1.DataNodeAdminService",
	HandlerType: (*DataNodeAdminServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "server.proto",
}
